DATALOADER:
  ASPECT_RATIO_GROUPING: false
  NUM_WORKERS: 4
DATASETS:
  TEST: ("smokenet_val", )
  TRAIN: ("smokenet_train", )
DATA_DIR_PATH: /home/rodriguedeschaetzen/smoke-detection-net/data/full/frames_100
EARLY_STOPPING:
  ENABLE: true
  MODE: max
  MONITOR: f1-score
  PATIENCE: 10
EVAL_ONLY: true
INPUT:
  CROP:
    ENABLED: false
MODEL:
  BACKBONE:
    FREEZE_AT: 2
    NAME: build_mnetv1_backbone
  CLSNET:
    ENABLE: true
    INPUT_SIZE: 224
    NUM_CLASSES: 16
  META_ARCHITECTURE: ClsNet
  MNET:
    OUT_FEATURES:
    - linear
    WIDTH_MULT: 0.5
  POS_WEIGHT:
  - 7
  - 3
  - 4
  - 9
  - 4
  - 1
  - 1
  - 4
  - 5
  - 2
  - 2
  - 7
  - 90
  - 32
  - 27
  - 74
  WEIGHTS: /home/rodriguedeschaetzen/smoke-detection-net/output/real_data_run-2/model_best.pth
OUTPUT_DIR: /home/rodriguedeschaetzen/smoke-detection-net/output/real_data_run-2
SEED: 999
SOLVER:
  BASE_LR: 0.0005
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 16
  MAX_ITER: 143071
  STEPS: (150000, 180000)
TEST:
  EVAL_PERIOD: 1430
VERSION: 2
