DATALOADER:
  ASPECT_RATIO_GROUPING: false
  NUM_WORKERS: 4
DATASETS:
  TEST: ("smokenet_val", )
  TRAIN: ("smokenet_train", )
DATA_DIR_PATH: /home/rodriguedeschaetzen/smoke-detection-net/data/full
EARLY_STOPPING:
  ENABLE: true
  MODE: max
  MONITOR: accuracy
  PATIENCE: 10
EVAL_ONLY: false
INPUT:
  CROP:
    ENABLED: false
MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: build_mnetv1_backbone
  CLSNET:
    ENABLE: true
    INPUT_SIZE: 224
    NUM_CLASSES: 16
  META_ARCHITECTURE: ClsNet
  MNET:
    OUT_FEATURES:
    - linear
    WIDTH_MULT: 0.25
  POS_WEIGHT:
  - 72
  - 32
  - 34
  - 67
  - 43
  - 11
  - 13
  - 39
  - 51
  - 22
  - 23
  - 67
  - 636
  - 223
  - 224
  - 507
  WEIGHTS: ''
OUTPUT_DIR: /home/rodriguedeschaetzen/smoke-detection-net/output/test_model
SEED: 999
SOLVER:
  BASE_LR: 0.01
  IMS_PER_BATCH: 16
  MAX_ITER: 113193
  STEPS: (150000, 180000)
TEST:
  EVAL_PERIOD: 1131
VERSION: 2
