DATALOADER:
  ASPECT_RATIO_GROUPING: false
  NUM_WORKERS: 4
DATASETS:
  TEST: ("smokenet_val", )
  TRAIN: ("smokenet_train", )
DATA_DIR_PATH: /home/raphael_menoni/smoke-detection-net/data/full/frames_100
EARLY_STOPPING:
  ENABLE: true
  MODE: max
  MONITOR: accuracy
  PATIENCE: 10
EVAL_ONLY: false
INPUT:
  CROP:
    ENABLED: false
MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: build_mnetv1_backbone
  CLSNET:
    ENABLE: true
    INPUT_SIZE: 224
    NUM_CLASSES: 4
  META_ARCHITECTURE: ClsNet
  MNET:
    OUT_FEATURES:
    - linear
    WIDTH_MULT: 0.25
  POS_WEIGHT:
  - 2
  - 3
  - 9
  - 9
  WEIGHTS: ''
OUTPUT_DIR: /home/raphael_menoni/smoke-detection-net/output/label_gridsize_2_threshold_1.0
SEED: 999
SOLVER:
  BASE_LR: 0.001
  IMS_PER_BATCH: 16
  MAX_ITER: 104725
  STEPS: (150000, 180000)
TEST:
  EVAL_PERIOD: 1047
VERSION: 2
