DATALOADER:
  ASPECT_RATIO_GROUPING: false
  NUM_WORKERS: 4
DATASETS:
  TEST: ("smokenet_val", )
  TRAIN: ("smokenet_train", )
DATA_DIR_PATH: /home/raphael_menoni/smoke-detection-net/data/full/bigsmoke
EARLY_STOPPING:
  ENABLE: true
  MODE: max
  MONITOR: accuracy
  PATIENCE: 10
EVAL_ONLY: false
INPUT:
  CROP:
    ENABLED: false
MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: build_mnetv1_backbone
  CLSNET:
    ENABLE: true
    INPUT_SIZE: 224
    NUM_CLASSES: 16
  META_ARCHITECTURE: ClsNet
  MNET:
    OUT_FEATURES:
    - linear
    WIDTH_MULT: 0.25
  POS_WEIGHT:
  - 27
  - 4
  - 26
  - 274800000
  - 5
  - 0
  - 11
  - 26
  - 248
  - 23
  - 8
  - 182
  - 274800000
  - 274800000
  - 71
  - 51
  WEIGHTS: ''
OUTPUT_DIR: /home/raphael_menoni/smoke-detection-net/output
SEED: 999
SOLVER:
  BASE_LR: 0.01
  IMS_PER_BATCH: 32
  MAX_ITER: 8587
  STEPS: (150000, 180000)
TEST:
  EVAL_PERIOD: 171
VERSION: 2
