DATALOADER:
  ASPECT_RATIO_GROUPING: false
  NUM_WORKERS: 4
DATASETS:
  TEST: ("smokenet_val", )
  TRAIN: ("smokenet_train", )
INPUT:
  CROP:
    ENABLED: false
MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: build_mnetv1_backbone
  CLSNET:
    ENABLE: true
    INPUT_SIZE: 224
    NUM_CLASSES: 16
  META_ARCHITECTURE: ClsNet
  MNET:
    OUT_FEATURES:
    - linear
    WIDTH_MULT: 0.25
OUTPUT_DIR: /Users/rodriguedeschaetzen/project_x/smoke-detection-net/output
SOLVER:
  BASE_LR: 0.1
  IMS_PER_BATCH: 64
  MAX_ITER: 101
  STEPS: (150000, 180000)
VERSION: 2
