DATALOADER:
  ASPECT_RATIO_GROUPING: false
  NUM_WORKERS: 4
DATASETS:
  TEST: ("smokenet_val", )
  TRAIN: ("smokenet_train", )
DATA_DIR_PATH: /home/rodriguedeschaetzen/smoke-detection-net/data/full/frames_100
EARLY_STOPPING:
  ENABLE: true
  MODE: max
  MONITOR: f1_score
  PATIENCE: 10
EVAL_ONLY: false
INPUT:
  CROP:
    ENABLED: false
MODEL:
  BACKBONE:
    FREEZE_AT: 2
    NAME: build_resnet_cls_backbone
  CLSNET:
    ENABLE: true
    INPUT_SIZE: 224
    NUM_CLASSES: 16
  META_ARCHITECTURE: ClsNet
  MNET:
    OUT_FEATURES:
    - linear
    WIDTH_MULT: 0.5
  POS_WEIGHT:
  - 7
  - 3
  - 4
  - 9
  - 3
  - 1
  - 1
  - 4
  - 5
  - 2
  - 2
  - 7
  - 71
  - 37
  - 36
  - 106
  RESNETS:
    DEPTH: 101
    NORM: FrozenBN
    OUT_FEATURES:
    - linear
  WEIGHTS: /home/rodriguedeschaetzen/smoke-detection-net/pretrained_models/X-101-32x8d.pkl
OUTPUT_DIR: /home/rodriguedeschaetzen/smoke-detection-net/output/proper-lr-test
SEED: 999
SOLVER:
  BASE_LR: 0.0005
  CHECKPOINT_PERIOD: 10000
  GAMMA: 0.1
  IMS_PER_BATCH: 16
  MAX_ITER: 143703
  STEPS: !!python/tuple
  - 1500
  - 2000
  - 10000
TEST:
  EVAL_PERIOD: 718
VERSION: 2
